# Generated by Django 2.2.4 on 2019-09-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0002_auto_20190927_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=5)),
                ('course_type', models.CharField(max_length=20)),
                ('department', models.CharField(blank=True, max_length=4)),
                ('course_name', models.CharField(max_length=30)),
                ('course_code', models.CharField(max_length=5)),
            ],
        ),
    ]
