# Generated by Django 2.2.4 on 2019-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0003_coursemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papermodel',
            name='image',
        ),
        migrations.AddField(
            model_name='papermodel',
            name='paper',
            field=models.FileField(default=None, upload_to='questionpaper'),
            preserve_default=False,
        ),
    ]
