# Generated by Django 2.2.4 on 2019-09-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='roll_no',
        ),
    ]
