# Generated by Django 2.2.4 on 2019-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0002_remove_userdetails_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='first_name',
            field=models.TextField(blank=True),
        ),
    ]
